//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaniCall.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaniCall.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Deleted.
        /// </summary>
        public static string lbl_accountDeleted {
            get {
                return ResourceManager.GetString("lbl_accountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Disabled.
        /// </summary>
        public static string lbl_accountDisabled {
            get {
                return ResourceManager.GetString("lbl_accountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string lbl_Cap_success {
            get {
                return ResourceManager.GetString("lbl_Cap_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string lbl_emailAddress {
            get {
                return ResourceManager.GetString("lbl_emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string lbl_error {
            get {
                return ResourceManager.GetString("lbl_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bulk request file is now successfully uploaded. In 20min all requests will be sent, so check in Pending Request page after 20min for status..
        /// </summary>
        public static string lbl_ExcelSuccess {
            get {
                return ResourceManager.GetString("lbl_ExcelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!.
        /// </summary>
        public static string lbl_exception {
            get {
                return ResourceManager.GetString("lbl_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string lbl_exportToExcel {
            get {
                return ResourceManager.GetString("lbl_exportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s).
        /// </summary>
        public static string lbl_files {
            get {
                return ResourceManager.GetString("lbl_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string lbl_in {
            get {
                return ResourceManager.GetString("lbl_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string lbl_input {
            get {
                return ResourceManager.GetString("lbl_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error Occurred!.
        /// </summary>
        public static string lbl_internalServerErrorOccurred {
            get {
                return ResourceManager.GetString("lbl_internalServerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string lbl_invalid {
            get {
                return ResourceManager.GetString("lbl_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ScanTime.
        /// </summary>
        public static string lbl_Invalid_ScanTime {
            get {
                return ResourceManager.GetString("lbl_Invalid_ScanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Validation Failed..
        /// </summary>
        public static string lbl_invalidToken {
            get {
                return ResourceManager.GetString("lbl_invalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string lbl_log {
            get {
                return ResourceManager.GetString("lbl_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfully.
        /// </summary>
        public static string lbl_msg_dataSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_dataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and Password Required.
        /// </summary>
        public static string lbl_msg_emailPasswordRequired {
            get {
                return ResourceManager.GetString("lbl_msg_emailPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error Occurred.
        /// </summary>
        public static string lbl_msg_internalServerErrorOccurred {
            get {
                return ResourceManager.GetString("lbl_msg_internalServerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string lbl_msg_invalidEmailAddress {
            get {
                return ResourceManager.GetString("lbl_msg_invalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address and Password.
        /// </summary>
        public static string lbl_msg_invalidEmailAddressPassword {
            get {
                return ResourceManager.GetString("lbl_msg_invalidEmailAddressPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Passowrd.
        /// </summary>
        public static string lbl_msg_invalidPassowrd {
            get {
                return ResourceManager.GetString("lbl_msg_invalidPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl_msg_loginFailed.
        /// </summary>
        public static string lbl_msg_loginFailed {
            get {
                return ResourceManager.GetString("lbl_msg_loginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Files Attached.
        /// </summary>
        public static string lbl_noFilesAttached {
            get {
                return ResourceManager.GetString("lbl_noFilesAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        public static string lbl_noRecordsFound {
            get {
                return ResourceManager.GetString("lbl_noRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string lbl_of {
            get {
                return ResourceManager.GetString("lbl_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string lbl_page {
            get {
                return ResourceManager.GetString("lbl_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lbl_password {
            get {
                return ResourceManager.GetString("lbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string lbl_profile {
            get {
                return ResourceManager.GetString("lbl_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string lbl_records {
            get {
                return ResourceManager.GetString("lbl_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Per Page.
        /// </summary>
        public static string lbl_recordsPerPage {
            get {
                return ResourceManager.GetString("lbl_recordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        public static string lbl_saveSuccessfully {
            get {
                return ResourceManager.GetString("lbl_saveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan temperature again. Interval too long after last scan..
        /// </summary>
        public static string lbl_scanTempInterval {
            get {
                return ResourceManager.GetString("lbl_scanTempInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan temperature. No temperature recorded..
        /// </summary>
        public static string lbl_scanTempNoData {
            get {
                return ResourceManager.GetString("lbl_scanTempNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lbl_search {
            get {
                return ResourceManager.GetString("lbl_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string lbl_success {
            get {
                return ResourceManager.GetString("lbl_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Created.
        /// </summary>
        public static string lbl_successfullyCreated {
            get {
                return ResourceManager.GetString("lbl_successfullyCreated", resourceCulture);
            }
        }
    }
}
